version: '2'
services:
    mediamanager-app:
        image: mediamanager
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mediamanager-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=MediaManager
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=mediamanager-elasticsearch:9300
        ports:
            - 8080:8080
    mediamanager-mongodb:
        extends:
            file: mongodb.yml
            service: mediamanager-mongodb
    mediamanager-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: mediamanager-elasticsearch
